services:
  cnn1d:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: cnn1d_model
    image: cnn1d:latest
    volumes:
      - .:/app
    environment:
     - PYTHONUNBUFFERED=1
    command: python cnn1d.py